### ISSUE TITLE
Is this project still under maintenance?

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/hdf5-java-bindings#7]
@lbergelson, as the major contributor here, could you tell me if this is still under maintenance? If so, it is possible to make the API use the `java.nio.Path`?

**Comment by droazen** [comment]
@magicDGS It is still under maintenance, however any proposed changes should be tracked under the main GATK issue tracker in https://github.com/broadinstitute/gatk. You should open an issue there.

**Comment by magicDGS** [comment]
Thanks, I will!
